SELECT p.TITULO, p.FECHAPUBLICACION, g.NOMBREGENERO, t.MODALIDAD 
FROM peliculas AS p, generos AS g, tipopeliculas AS t 
WHERE p.GENERO = g.CODIGOGENERO AND p.TIPOPELICULA = t.CODIGOENTREGA 
ORDER BY t.CODIGOENTREGA ASC, p.TITULO ASC